name: Destroy staging (manual)
on: { workflow_dispatch: {} }

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/CLI@v2
        with:
          inlineScript: |
            az account set --subscription "${{ secrets.AZ_SUBSCRIPTION_ID }}"
            az group delete -n "${{ secrets.STAGING_RG }}" -y --no-wait